export const NAV_TYPES = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  OTP: 'OTP',
  HOME_SCREEN: 'HOME_SCREEN',
  CHAT_MESSAGE_SCREEN: 'CHAT_MESSAGE_SCREEN',
  CONTACTS_SCREEN: 'CONTACTS_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
  CAMERA_VIEW: 'CAMERA_VIEW',
  STATUS_VIEW: 'STATUS_VIEW',
};
